apiVersion: apps/v1
kind: Deployment
metadata:
  name: temperatura
spec:
  selector:
    matchLabels:
      app: temperatura
  template:
    metadata:
      labels:
        app: temperatura
    spec:
      containers:
      - name: temperatura
        image: joaomartinelli/conversao-temperatura:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  selector:
    app: web
  ports:
  - port: 80
    targetPort: 8080

